name: Use labels defined in JSON only

on:
  push:
    paths:
      - ".github/*"
  workflow_dispatch:

jobs:
  Label:
    permissions: write-all
    #permissions:
    #  pull-requests: write
    #  contents: read
    name: DefaultLabelsActions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lannonbr/issue-label-manager-action@4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete: true
